### ISSUE TITLE
Trading Fees in Backtest.

### ISSUE THREAD

**Issue by chasemb** [nkaz001/algotrading-example#4]
How are trading fees calculated in your backtests?

When trades are closed, is it through a market order or limit? If limit, is there some sort of stop-loss in place?

Thanks.

**Comment by nkaz001** [comment]
Please see `predict_njit` method in the notebook file.

In the backtest, a buy order price is set as less than or equal to the best bid, and a sell order price is set as greater than or equal to the best offer. But I conservatively applied the taker fee in the optimization and checked the results in both the maker fee and the taker fee configurations.

There is no stop-loss logic.

**Comment by chasemb** [comment]
Ah, at first I was searching for the method and came up empty handed.  I found it in your previous repo.

Any interest in running this thing live with some capital? We'd be very interested!  chase (at) discovermedia (dot) com.
