### ISSUE TITLE
how can i contact you i have some questions about your project ?

### ISSUE THREAD

**Issue by Clairewangxiaotong** [nkaz001/algotrading-example#7]
Hi Thanks for your share but I have some questions,may I have you email address or something else which I can contact you ?

**Comment by nkaz001** [comment]
If you have a question, please leave your question here.

**Comment by Clairewangxiaotong** [comment]
[Errno 2] No such file or directory: 'btcusdt_data'

when I run [image: image.png],please.
Thank you so much.
nkaz001 ***@***.***> 于 2022年10月16日周日 下午9:09写道：

**Comment by Clairewangxiaotong** [comment]
So the   btcusdt_data file is same as the df  in the tardis-process.ipynb
<https://github.com/nkaz001/data-tardis/blob/master/tardis-process.ipynb>
,right?

nkaz001 ***@***.***> 于2022年10月17日周一 18:53写道：

**Comment by nkaz001** [comment]
not exactly the same as tardis-process.ipynb is written for BitMEX but data is processed in the same way.

**Comment by Clairewangxiaotong** [comment]
sure,I mean if I change the name of df.csv to btcusdt_data, so it can be
run perfectly, right?

nkaz001 ***@***.***> 于2022年10月17日周一 20:11写道：

**Comment by nkaz001** [comment]
With a proper df it runs without an error. just for your information, the backtesting notebook reads pickled df.

**Comment by Clairewangxiaotong** [comment]
I see, thanks.

nkaz001 ***@***.***> 于 2022年10月17日周一 下午9:11写道：
