### ISSUE TITLE
information

### ISSUE THREAD

**Issue by pradeephyd** [nkaz001/algotrading-example#8]
can we add an interface for equities? 
and how this was implemented in this 
[https://www.reddit.com/r/algotrading/comments/p8e5wl/any_orderbook_traders/](url)

**Comment by nkaz001** [comment]
Could you elaborate on what the interface is? I think the backtest could be done in the same way. You just need data.
 
Regarding my implementation of any_orderbook_traders post, please see the comment at the beginning in https://github.com/nkaz001/algotrading-example/blob/master/crypto-scratch/xbtusd-weighted-depth-orderbook-price-simple-backtest-hedge.ipynb

**Comment by pradeephyd** [comment]
Thanks for your response, I mean can we add equites interface to pull data for back testing.

**Comment by nkaz001** [comment]
You need full depth of market data for equities and data format can vary depending on a data vendor. So you need to convert the data into the form that this backtest uses.

Please see https://github.com/nkaz001/data-tardis/blob/master/tardis-process.ipynb
You can see how I converted a certain csv format of full depth of market data to DataFrame I used.

**Comment by pradeephyd** [comment]
That's really great. And another piece of information with this order flow imbalance strategy are you doing real-time trades?  
I`m planning to connect TD Ameritrade API to get bid-ask and integrate it to your order-book. so if this has good returns, then I`ll push the interface here. Thank you.
